Bump to 5.1

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,32 +1,38 @@
-#!/bin/sh
-set -e
-export PATH="$(dirname "$0")/../bin:$PATH"  # Use binstubs
+#!/usr/bin/env ruby
+require 'pathname'
+require 'fileutils'
+include FileUtils
 
-if [ "$1" = "-v" ]; then
-  exec 3>&1
-else
-  exec 3>/dev/null
-fi
+# path to your application root.
+APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
 
-# Wipe out logs and scss cache.
-echo "Cleaning out old logs"
-{ rm -f log/*
-} >&3 2>&1
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Install dependencies
-echo "Installing libraries and plugins"
-{ bundle
-} >&3 2>&1
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
 
-# Wipe and load the database unless KEEPDB=1 env var is set.
-if [ -z "$KEEPDB" ]; then
-  echo "Reloading the database"
-  { rake db:create:all db:drop:all db:setup --trace
-    rake db:test:prepare --trace
-  } >&3 2>&1
-fi
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-echo "Restarting Pow/Passenger"
-touch tmp/restart.txt
+  # Install JavaScript dependencies if using Yarn
+  # system('bin/yarn')
 
-echo "Done!"
+
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   cp 'config/database.yml.sample', 'config/database.yml'
+  # end
+
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
+
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
